"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ui_widget.py']
DATA_FILES = ['haarcascade_eye.xml','haarcascade_frontalface_default.xml','haarcascade_lefteye_2splits.xml','haarcascade_righteye_2splits.xml']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
